name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README file
        run: |
          echo "## Updated Section" >> README.md
          echo "This section was added by GitHub Actions." >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m 'Update README with new content'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
