name: Count Dev Branch Commits

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  count-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Fetch dev branch history
        run: |
          git fetch origin main
          git checkout main

      - name: Count commits by engineer
        run: |
          echo "Counting commits for each engineer on the dev branch..."
          git log --pretty=format:"%an" | sort | uniq -c | sort -nr

      - name: Output detailed commit count
        run: |
          echo "Commit count per engineer on the dev branch:"
          # Fetch commit history, count commits per engineer, and output
          git log --pretty=format:"%an" | sort | uniq -c | while read -r count engineer; do
            echo "$engineer has made $count commits"
          done
