name: Test Scheduled Push

on:
  schedule:
    - cron: '0 0 * * *'   # Runs at 12:00 AM
    - cron: '0 10 * * *'  # Runs at 12:00 PM (noon)
    - cron: '0 12 * * *'  # Runs at 10:00 PM
    - cron: '0 23 * * *'  # Runs at 11:00 PM

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Make changes
        run: |
          echo "This is a test update at $(date)" >> README.md

      - name: Commit and Push changes
        if: github.actor != 'github-actions[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main
          git add README.md
          git commit -m "Update README with new content at $(date)"
          git push origin main
