name: Test Scheduled Push

on:
  schedule:
    - cron: '10 2 * * *'

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Make changes
        run: |
          echo "This is a test update at $(date)" >> README.md

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Update README with new content at $(date)"
          git push origin main
